server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always

spring:
  h2:
    console:
      enabled:true

  datasource:
    url: jdbc:h2:mem:userDB;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show-sql: true
        use-sql-comments: false
        format-sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"



